### PR TITLE
A nodejs example

### PR DESCRIPTION
**Pull request by hrgdavor**
It took me a while to find a way to use it in node. I would like others to have it available on main page in readme too :)

### CODE REVIEW

**Review by pimterry — COMMENTED** [review]
Hi @hrgdavor, thanks for the contribution! Definitely open to clarifying the readme around cases like that.

The change here doesn't look unreasonable, but I think the existing example should actually also work for Node - modern node now supports fetch and web streams too, so there shouldn't be a major issue there.

Can you explain more about how that didn't work for you? Or was it just that you wanted an FS example instead of a fetch example?

**Comment by hrgdavor** [comment]
simply the example fetch throws error on node 20... also does not work in bun.

```js
const compressedResponse = await fetch('somefile.xz');

// node throws: TypeError: Failed to parse URL from somefile.xz
// bun throws:  TypeError: fetch() URL is invalid
```

**Comment by pimterry** [comment]
Ah yes - that's a placeholder, the assumption is that you'd use the URL of a xz file you'd like to download somewhere (not a local file). Good point though, that should be clearer.

It sounds like you're reading from disk then, not a file you're downloading from the web? I'd been assuming most xz content was file downloads, but of course it should work for any other use cases too.

If you're trying to read from disk, you probably want to start with `Readable.toWeb(fs.createReadStream(filename))` which will give you a web file stream.

**Comment by pimterry** [comment]
I've now expanded on this, and combined the explanation above with your example in the README here: https://github.com/httptoolkit/xz-decompress/commit/0cdec25fe3e91367e5e2feebfb458a41c21e5431

**Pull request closed without merging**
